import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { QueryProvider } from "@/context/QueryProvider";
import { ToastProvider } from '@/components/ui/use-toast'
import { Toaster } from '@/components/ui/toaster'

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap", // Use 'swap' to avoid FOIT
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <QueryProvider>
          <ToastProvider>
            <AuthContextProvider>
              {children}
            </AuthContextProvider>
            {/* Global pop-up notifications */}
            <Toaster />
          </ToastProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
